import Good from '../interfaces/good'

const data: Good[] = [
    {
        srcImg: ['/assets/mramorGoods/polianfBriz.webp', '/assets/mramorGoods/polianfBriz_2.webp'],
        name: 'Polianf Briz',
        price: 7000,
        title: 'Мраморная плитка, погружающая в мир океана',
        sizes: [200, 300],
        thickness: 20,
        country: 'Poland',
        colors: ['brown', 'pink'],
    },
    {
        srcImg: '/assets/mramorGoods/briCold.webp',
        name: 'Bri Cold',
        price: 6800,
        title: 'Мраморная плитка из мира льда',
        sizes: [200, 300],
        thickness: 20,
        country: 'Poland',
        colors: ['blue'],
    },
    {
        srcImg: '/assets/mramorGoods/iceB.jpg',
        name: 'Ice B',
        price: 6800,
        title: 'Мраморная плитка из мира льда',
        sizes: [200, 300],
        thickness: 20,
        country: 'India',
        colors: ['blue'],
    },
    {
        srcImg: '/assets/mramorGoods/piWave.jpg',
        name: 'Pi Wave',
        price: 6800,
        oldPrice: 7000,
        title: 'Мраморная плитка из мира льда',
        sizes: [200, 300],
        thickness: 20,
        country: 'India',
        colors: ['pink'],
    },
    {
        srcImg: ['/assets/mramorGoods/GRBi.jpg', '/assets/mramorGoods/GRBi_2.jpg'],
        name: 'GR Bi',
        price: 6800,
        title: 'Мраморная плитка с коррозией',
        sizes: [200, 300],
        thickness: 20,
        country: 'India',
        colors: ['blue', 'green'],
    },
    {
        srcImg: '/assets/mramorGoods/white.jpg',
        name: '.White.',
        price: 6100,
        title: 'Классическая мраморная плитка',
        sizes: [200, 300, 500],
        thickness: 16,
        country: 'India',
        colors: ['white'],
    },
    {
        srcImg: '/assets/mramorGoods/black.jpg',
        name: '.Black.',
        price: 6100,
        title: 'Классическая мраморная плитка',
        sizes: [200, 300, 500],
        thickness: 16,
        country: 'India',
        colors: ['black'],
    },
    {
        srcImg: '/assets/mramorGoods/RoliOran.jpg',
        name: 'Roli Oran',
        price: 6800,
        title: 'Мраморная плитка с коррозией',
        sizes: [200, 300],
        thickness: 20,
        country: 'Poland',
        colors: ['orange'],
    },
    {
        srcImg: '/assets/mramorGoods/BYi.jpg',
        name: 'B Yi',
        price: 6800,
        title: 'Мраморная плитка с коррозией',
        sizes: [200, 300],
        thickness: 20,
        country: 'Poland',
        colors: ['black'],
    },
    {
        srcImg: '/assets/mramorGoods/EurGY.jpg',
        name: 'Eur GY',
        price: 6800,
        title: 'Мраморная плитка с коррозией',
        sizes: [200, 300],
        thickness: 16,
        country: 'Poland',
        colors: ['grey'],
    },
    {
        srcImg: '/assets/mramorGoods/BArt.jpg',
        name: 'B Art',
        price: 6200,
        oldPrice: 7200,
        title: 'Мраморная плитка с коррозией',
        sizes: [200, 300],
        thickness: 16,
        country: 'Poland',
        colors: ['blue'],
    },
    {
        srcImg: '/assets/mramorGoods/EurGY.jpg',
        name: 'Mram GY',
        price: 7200,
        title: 'Мраморная плитка с коррозией',
        sizes: [200, 300],
        thickness: 16,
        country: 'Egypt',
        colors: ['grey'],
    },
    {
        srcImg: '/assets/mramorGoods/MnttRange.jpg',
        name: 'Mntt Range',
        price: 7200,
        title: 'Мраморная плитка с коррозией',
        sizes: [200, 300],
        thickness: 16,
        country: 'Egypt',
        colors: ['green'],
    },
    {
        srcImg: '/assets/mramorGoods/WVBlue.jpg',
        name: 'WV Blue',
        price: 7200,
        oldPrice: 8000,
        title: 'Мраморная плитка с коррозией',
        sizes: [200, 300],
        thickness: 22,
        country: 'India',
        colors: ['blue'],
    },
    {
        srcImg: '/assets/mramorGoods/Plain&City.jpg',
        name: 'Plain&City',
        price: 7200,
        oldPrice: 8000,
        title: 'Мраморная плитка с текстурой успокоения',
        sizes: [300],
        thickness: 20,
        country: 'India',
        colors: ['grey'],
    },
    {
        srcImg: '/assets/mramorGoods/Plain&City.jpg',
        name: 'Breeze',
        price: 6000,
        title: 'Мраморная плитка с коррозией',
        sizes: [200, 300, 500],
        thickness: 20,
        country: 'India',
        colors: ['blue'],
    },
    {
        srcImg: ['/assets/mramorGoods/BWStreaks.jpg', '/assets/mramorGoods/BWStreaks_2.jpg'],
        name: 'BW Streaks',
        price: 6600,
        title: 'Мраморная плитка с текстурой успокоения',
        sizes: [200, 300],
        thickness: 22,
        country: 'Egypt',
        colors: ['blue', 'violet'],
    },
]

export default data;